title: VEdition Documentation
description: Documentation about Goethe Venetian Epigrams digital edition
theme: just-the-docs

url: https://vedph.github.io/gve-doc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

mermaid:
  version: "11.4.1"

enable_copy_code_button: true

nav_sort: case_insensitive
